#!/usr/bin/env python

import rospy

from std_msgs.msg import Bool
from std_srvs.srv import Empty

def reset_vision_callback(msg):
    if msg.data == False: return

    rospy.loginfo('Received vision reset request')
    reset_vision()

if __name__ == '__main__':
    rospy.init_node('pass_control')

    global reset_vision
    rospy.wait_for_service('reset_vision')
    reset_vision = rospy.ServiceProxy('reset_vision', Empty)

    rospy.Subscriber('reset_vision_request', Bool, reset_vision_callback)

    rospy.spin()
