#!/usr/bin/env python

import rospy

from sensor_msgs.msg import CameraInfo, RegionOfInterest

def republish(msg):
    msg.roi = roi
    out_pub.publish(msg)

if __name__ == '__main__':
    rospy.init_node('selfie_define_roi')

    global roi
    roi = RegionOfInterest(
        rospy.get_param('~x_offset', 0),
        rospy.get_param('~y_offset', 0),
        rospy.get_param('~height', 0),
        rospy.get_param('~width', 0),
        rospy.get_param('~do_rectify', False)
    )

    in_topic = rospy.get_param('~in_topic')
    out_topic = rospy.get_param('~out_topic')

    global out_pub
    out_pub = rospy.Publisher(out_topic, CameraInfo, queue_size=10)
    in_sub = rospy.Subscriber(in_topic, CameraInfo, republish)

    rospy.spin()
